services:
  1c-monitor:
    image: mishan358/1c-releases-monitor:latest
    build: .
    container_name: 1c-releases-monitor
    restart: unless-stopped

    # ← Это обязательно для чтения .env
    env_file:
      - .env

    volumes:
      - ./data:/data

    # === Логирование ===
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    environment:
      - PYTHONUNBUFFERED=1